### ISSUE TITLE
Problemas na pesquisa de ingredientes

### ISSUE THREAD

**Issue by andreusmotta** [Robemac2/Projeto-Doceria#2]
Quando faço uma pesquisa na parte de ingredientes com os dizeres em maiúsculo ele não acha os itens.

![image](https://github.com/Robemac2/Projeto-Doceria/assets/110033664/4bfeb8c0-4af3-44b1-ada5-728802c8b3d6)

**Comment by Robemac2** [comment]
Problema corrigido no commit `06e147e`, a pesquisa agora é case insensitive.
