### ISSUE TITLE
A unidade "Kilogramas" está em maíusculo

### ISSUE THREAD

**Issue by andreusmotta** [Robemac2/Projeto-Doceria#3]
Todas as unidades estão começando com minusculo, menos a "Kilogramas"

![image](https://github.com/Robemac2/Projeto-Doceria/assets/110033664/beefcc91-601b-4d47-be24-29c1edf14402)

**Comment by Robemac2** [comment]
As unidades "Kilogramas" e "Litros" estão em maiúsculo com o objetivo de chamar a atenção e facilitar a distinção na escolha das unidades.
